PAGE = """<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>symbolgraph Dashboard</title>
<style>body{font:15px system-ui;margin:0;background:#f5f7fb;color:#172033}main{max-width:1100px;margin:auto;padding:20px}section,.card{background:white;border:1px solid #dce2ec;border-radius:10px;padding:16px;margin:12px 0}h1{margin-top:0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.metric{font-size:24px;font-weight:700}.muted{color:#687386}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:7px;border-bottom:1px solid #eee}button{cursor:pointer}input{padding:9px;width:min(500px,80%)}pre{white-space:pre-wrap}@media(max-width:600px){main{padding:10px}table{font-size:12px}}</style></head>
<body><main><h1>symbolgraph Dashboard</h1><div id='health' class='card'>Loading health…</div><div id='metrics' class='grid'></div><section><h2>Sessions</h2><div id='sessions'>Loading sessions…</div></section><section><h2>Search</h2><form id='form'><input id='q' placeholder='Search symbols'><button>Search</button></form><div id='results'></div></section><section><h2>Selected session</h2><div id='detail' class='muted'>Select a session above.</div></section></main>
<script>
const $=id=>document.getElementById(id); const esc=s=>String(s??'');
async function get(u){let r=await fetch(u);let x=await r.json();if(!r.ok)throw Error(x.error||r.status);return x}
function cell(v){let e=document.createElement('td');e.textContent=esc(v);return e}
async function load(){try{let [h,s,ss]=await Promise.all([get('/api/health'),get('/api/status'),get('/api/sessions')]);$('health').textContent=`${h.project_path} — index: ${h.index_present?'ready':'missing'}, sessions: ${h.session_database_present?'ready':'missing'}`; let m=[['Files',s.document_count],['Symbols',s.symbol_count],['Chunks',s.chunk_count],['Relationships',s.relationship_count],['Active sessions',s.active_sessions],['Retrievals',s.retrieval_events]];m.forEach(([a,b])=>{let d=document.createElement('div');d.className='card';d.innerHTML='';let l=document.createElement('div');l.textContent=a;let n=document.createElement('div');n.className='metric';n.textContent=esc(b);d.append(l,n);$('metrics').append(d)});let t=document.createElement('table');ss.sessions.forEach(x=>{let tr=document.createElement('tr');let b=document.createElement('button');b.textContent=x.id.slice(0,8);b.onclick=()=>detail(x.id);let td=document.createElement('td');td.append(b);tr.append(td,cell(x.status),cell(x.started_at),cell(x.retrieval_event_count));t.append(tr)});$('sessions').textContent='';$('sessions').append(t)}catch(e){$('health').textContent='Error: '+e.message}}
async function detail(id){try{let x=await get('/api/sessions/'+encodeURIComponent(id));let d=$('detail');d.textContent='';let h=document.createElement('h3');h.textContent=x.session.id;d.append(h);['decisions','code_areas','retrieval_events'].forEach(k=>{let h=document.createElement('h4');h.textContent=k.replaceAll('_',' ');d.append(h);(x[k]||[]).forEach(v=>{let p=document.createElement('p');p.textContent=JSON.stringify(v);d.append(p)})})}catch(e){$('detail').textContent='Error: '+e.message}}
$('form').onsubmit=async e=>{e.preventDefault();$('results').textContent='Loading…';try{let x=await get('/api/search?q='+encodeURIComponent($('q').value));let t=document.createElement('table');(x.results||[]).forEach(v=>{let tr=document.createElement('tr');[v.symbol_name,v.qualified_name,v.kind,v.relative_path,v.location,v.score].forEach(z=>tr.append(cell(z)));t.append(tr)});$('results').textContent='';$('results').append(t)}catch(e){$('results').textContent='Error: '+e.message}};load();
</script></body></html>"""
